[package]
name = "key-mods-rs"
version = "0.1.0"
authors = ["shiro <shiro@usagi.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.2"
input-linux-sys = "0.3.1"
libc = "0.2.71"
anyhow = "1.0"
x11rb = "0.7.0"
tokio = { version = "0.3.4", features = ["full"] }
futures = "0.3"
lazy_static = "1.4.0"