[package]
name = "key-mods-rs"
version = "0.1.0"
authors = ["shiro <shiro@usagi.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.2"
input-linux-sys = "0.3.1"
libc = "0.2.71"
