[package]
name = "key-mods-rs"
version = "0.1.0"
authors = ["shiro <shiro@usagi.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input-linux-sys = "0.3.1"
libc = "0.2.71"
tap = "1.0.1"
itertools = "0.10.0"
anyhow = "1.0"
x11rb = "0.7.0"
tokio = { version = "0.3.4", features = ["full"] }
futures = "0.3"
lazy_static = "1.4.0"
async-recursion = "0.3.2"
nom = "6.1.2"
#evdev-rs = "0.5.0"
evdev-rs = { path = "evdev-rs" }
walkdir = "2.3.2"
regex = "1.4.5"
unicode-xid = "0.2.1"
notify = "4.0.16"

[[bin]]
name = "key-mods-rs"
path = "src/main.rs"

#[[bin]]
#name = "dev-test"
#path = "src/device/device-test.rs"
